### ISSUE TITLE
Refresh serverů

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/hJOPrcsDebugger#2]
* [x] Server zůstává v seznamu serverů, i když byl vypnut a pak spušten manuální refresh. Manuální refresh by měl smazat seznam nalezených serverů.
* [x] Nechat animaci po swipu dolů manuálního refreshe točit tak dlouho, jak dlouho trvá UDP timeout na příchozí data, ať animace jasně reflektuje, kdy se může seznam ještě měnit a kdy ne.
* [x] Refresh nefunguje: stav existujího serveru se neaktualizuje (např. offline/online).

**Comment by NavratilovaH** [comment]
Online offline se mi zdá, že už funguje, asi jsem to opravila díky těm dvěma ostatním issues. Můžeš zkontrolovat prosím?

**Comment by malinajan** [comment]
Funguje.
