### ISSUE TITLE
Releasnout modul při odchodu z aktivity modulu

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/hJOPrcsDebugger#6]
V současné době vydá zvuk změny při změně vstupu modulu, na který se už nedívám, protože jsem odešel pryč tlačítkem zpět.

**Comment by NavratilovaH** [comment]
To jsem nebyla schopna zreprodukovat. Jakože mě to nedělalo zvuk, všechno se tvářilo ok.

**Comment by malinajan** [comment]
Reprodukováno. RELEASE se posílá na server až po otevření aktivity dalšího modulu
